export const COLORS = {
    alto: "#DDDDDD",
    apricotWhite: "#FFFEEB",
    background: "#F1F3F6",
    black: "#000000",
    white: "#FFFFFF",
    primaryTextColor: "#000000",
    subTextColor: "#7A7A7A",
    anchorColor: "#2874F0",
    danger: "#FF6161",
    success: "#388E3C",
    warning: "#FFA000",
    borderColor: "#F0F0F0",
    placeHolder: "#AEB1B3",
    backdrop: "rgba(0, 0, 0, 0.54)",
    transparent: "transparent",
    green: "#EDF5E1",
    lightBlue: "#bdf0ff",
    gallery: "#EEEEEE",
    primary: "#FBAD23",
};
